### PR TITLE
new sidebar design

### PR DESCRIPTION
**Pull request by freeman-lab**
Proposal for an alternate design of the sidebar (and overall layout). It puts the table of contents behind a shaded region. It's a bit more similar to classic documentation sites, and a bit more traditional, but maybe easier to understand. Although I liked the minimalism of the current version, with the new one, I find my eyes are more easily guided to the right place.

Here are screenshots from a full doc site before and after the change.

screen shot 2016-04-05 at 10 51 02 am

screen shot 2016-04-05 at 10 53 28 am

And here's a live site with the new layout 

http://docs.thunder-project.org/

Suggested by @sofroniewn.

### CODE REVIEW

**Comment by sofroniewn** [comment]
I agree that the shading just makes it a little easier to visually parse

**Comment by sethvincent** [comment]
Nice! That looks great.

**Comment by mathisonian** [comment]
:+1: on the new sidebar. my only suggestion would be that the style for the "selected" section is a little hard to scan now. heres a quick alt for that 
screen shot 2016-04-05 at 11 51 10 am

**Comment by freeman-lab** [comment]
@mathisonian awesome idea, just added "conlen selections"

**Comment by freeman-lab** [comment]
thanks for the feedback all! merging this in

**Pull request merged**
