### PR TITLE
contributor icons

### PR DESCRIPTION
**Pull request by freeman-lab**
This PR shows contributors on a doc page as proposed in https://github.com/freeman-lab/minidocs/issues/31

Contributors are specified in `contents` like this

```js
'overview': {
  'about': {
    file: 'about.md',
    link: 'http://github.com/freeman-lab/minidocs',
    contributors: ['@sethvincent', '@yoshuawuyts', '@freeman-lab']
  }
}
```

The result is

screen shot 2016-06-27 at 9 35 26 pm

And the layout handles large numbers of contributors pretty well

screen shot 2016-06-27 at 9 36 15 pm

The icons are links to user's GitHub pages.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
radddd! :tada:

**Comment by sethvincent** [comment]
Cooool.

The fixed position is a little messy:

screen shot 2016-06-28 at 11 38 33 am

Could use `absolute` position for the contributor container instead.

**Comment by sethvincent** [comment]
Getting an error when using the cli with this branch:

```
SyntaxError: Unexpected token (2:9) while parsing file: /Users/sdv/workspace/freeman-lab/minidocs/node_modules/github-username/node_modules/got/package.json
    at Parser.pp.raise (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.semicolon (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2243:59)
    at Parser.pp.parseExpressionStatement (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2677:8)
    at Parser.pp.parseStatement (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2462:160)
    at Parser.pp.parseBlock (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseStatement (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2443:19)
    at Parser.pp.parseTopLevel (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/Users/sdv/workspace/freeman-lab/minidocs/node_modules/falafel/index.js:22:15)
```

Not sure yet what it is, but has something to do with the `got` module not parsing in the browserify bundle. Weird that it only happens with the cli, though.

**Comment by sethvincent** [comment]
@freeman-lab I added a small commit to make sheetify not run globally. The cli now works as expected.

The `got` module requires it's own package.json file and when that json file is parsed during the sheetify transform it throws a syntax error.

@yoshuawuyts I started looking into how sheetify might ignore parsing json files as that could be a good fix, but haven't gotten far yet. It's something to do with falafel/acorn.

**Comment by freeman-lab** [comment]
Thanks everyone! Fixed the CSS issue @sethvincent , think we're ready to 🚢  !

**Pull request merged**
