### PR TITLE
mobile styles

### PR DESCRIPTION
**Pull request by sethvincent**
Initial work on responsive styles!

screen shot 2016-07-20 at 2 32 56 pm
screen shot 2016-07-20 at 2 33 09 pm

A little more cleanup I'd like to do (like better padding for the menu items in the mobile view) but wanted to get this open for feedback.

### CODE REVIEW

**Comment by sethvincent** [comment]
I tried this out with the binder docs and it's working alright.

**Comment by freeman-lab** [comment]
Looking nice @sethvincent! Might make the menu button a little bigger. And agree about more menu padding. How does scrolling when the menu is larger than the full screen?

**Comment by sethvincent** [comment]
@freeman-lab oh right i need to make it scroll the the menu is long. fixing that now.

**Comment by sethvincent** [comment]
ok, menu is now scrollable, and made the menu button a little bigger.

**Comment by freeman-lab** [comment]
cool @sethvincent !

**Pull request merged**
