### PR TITLE
Add support for customised css

### PR DESCRIPTION
**Pull request by fraserxu**
see https://github.com/freeman-lab/minidocs/issues/1

* Add a `opts.theme` to options to load `theme.css`
* Update `npm start` command for `budo` because 

```JavaScript
# default html will use src="static/bundle.js"
budo src/index.js:static/bundle.js
```

### CODE REVIEW

**Comment by freeman-lab** [comment]
@fraserxu Nice! :+1:  and thanks for the standard fixes =)

Only minor thing: I think maybe we should rename `theme` -> `style` and `theme.css` -> `style.css` , cause  I was thinking of separately adding a `theme` option that would do a string lookup against some prebuilt styles, e.g. `"light"` `"dark"` etc. Sound good?

**Comment by fraserxu** [comment]
Totally make sense! Updating it..

**Comment by freeman-lab** [comment]
awesome!

**Comment by freeman-lab** [comment]
published as 1.1.0

**Pull request merged**
