### PR TITLE
use choo in minidocs

### PR DESCRIPTION
**Pull request by sethvincent**
This PR closes issues #3 and #22 and introduces choo & sheetify for building and styling the UI components and managing application state (which is super minimal still).

Benefits this adds:

- using html5 pushstate each page of the docs has a pathname
- when using the cli tool each page of the docs is generated as an html file, so when using services like GitHub pages that don't support html5 pushstate, the app still works. it's the static site equivalent of rendering views on the server first then having the front-end app take over on page load.
- code is a little easier to reason about
- uses this fun new choo project 😄

### CODE REVIEW

**Comment by sethvincent** [comment]
This would also effectively close pull requests #23 and #19.

**Comment by freeman-lab** [comment]
wooooo choooo 🚂 🚋 🚋 🚋 🚋 🚋  this looks super awesome @sethvincent will give it a whirl and take a look over the code just for my own education

**Comment by sethvincent** [comment]
Cool. I'll try it out with the send-action and binder docs to make sure i didn't miss anything.

**Comment by freeman-lab** [comment]
Oh great idea!

**Comment by sethvincent** [comment]
ok, i did a round of fixes for send-action & binder docs.

the two of them make for good use cases as one is built with the cli & one is just the js api.

i'm realizing the only downside of this PR is the js api is _slightly_ more verbose:

```js
var minidocs = require('minidocs')
var read = require('read-directory')
var contents = require('./contents')

var app = minidocs({
  contents: contents,
  markdown: read.sync('./markdown', { extensions: false }),
  logo: 'logo.svg'
})

var tree = app.start()
document.body.appendChild(tree)
```

### main changes to the js api:

- recommending use of `read-directory` rather than `include-folder` which i switched to mostly for windows compatibility.
- the addition of choo's `.start()` method and adding the tree to the dom:

```js
var tree = app.start()
document.body.appendChild(tree)
```

The above two lines are mostly boilerplate, which is mildly annoying, but the cli relies on getting the `app` object so it can run `app.toString()` to generate html files.

**Comment by freeman-lab** [comment]
this LGTM!

**Pull request merged**
